In [1]:
import numpy as np

In [2]:
# EXERCISE: TRY YOURSELF
A = np.array([[-2, 1], [12, -3]])

In [3]:
evals, evecs = np.linalg.eig(A)

In [4]:
evals

array([ 1., -6.])

In [5]:
evecs

array([[ 0.31622777, -0.24253563],
       [ 0.9486833 ,  0.9701425 ]])

In [6]:
evecs[:,0] / np.array([1/3, 1])

array([0.9486833, 0.9486833])

In [7]:
evecs[:,1] / np.array([-1/4, 1])

array([0.9701425, 0.9701425])

In [8]:
evecs[:,0] @ evecs[:,0]

1.0000000000000002

In [9]:
# EXERCISE: ARE THE EIGENVECTORS ORTHOGONAL?
evecs[:,0].dot(evecs[:,1])

0.8436614877321075

In [10]:
# A^TA and AA^T have the same eigenvalues
A = np.random.randn(5, 3)

In [11]:
evals, _ = np.linalg.eig(A.T @ A)
evals

array([3.20865468, 2.0118694 , 0.3243978 ])

In [12]:
evals, _ = np.linalg.eig(A @ A.T)
evals

array([ 3.20865468e+00,  2.01186940e+00,  3.24397802e-01, -4.81847696e-17,
        4.98343978e-17])

In [13]:
# USE eigh FOR SYMMETRIC/HERMITIAN MATRICES
evals, _ = np.linalg.eigh(A.T @ A)
evals

array([0.3243978 , 2.0118694 , 3.20865468])

In [14]:
evals, _ = np.linalg.eigh(A @ A.T)
evals

array([-1.28896079e-16,  1.57519016e-16,  3.24397802e-01,  2.01186940e+00,
        3.20865468e+00])

In [15]:
# WHY ARE ALL THE EIGENVALUES POSITIVE?

In [16]:
# EIGENVALUES OF INVERSE
B = np.linalg.inv(A.T @ A)
evals, _ = np.linalg.eigh(B)
evals

array([0.3116571 , 0.49705016, 3.08263495])

In [17]:
evals, _ = np.linalg.eig(A.T @ A)
1 / evals

array([0.3116571 , 0.49705016, 3.08263495])

In [18]:
# WILL THE EIGENVECTORS BE ORTHOGONAL?
evals, evecs = np.linalg.eigh(A.T @ A)
evecs

array([[ 0.12681878,  0.93987975, -0.31708525],
       [ 0.39378351,  0.24569318,  0.88575923],
       [ 0.91041284, -0.23719385, -0.33895064]])

In [19]:
evecs[:,0] @ evecs[:,1]

2.7755575615628914e-17

In [20]:
evecs[:,0] @ evecs[:,2]

0.0

In [21]:
evecs @ evecs.T

array([[ 1.00000000e+00,  1.84817720e-17, -5.56158808e-17],
       [ 1.84817720e-17,  1.00000000e+00, -2.44711648e-17],
       [-5.56158808e-17, -2.44711648e-17,  1.00000000e+00]])

In [22]:
# DETERMINANT
np.linalg.det(A.T @ A)

2.0941156826060605

In [23]:
np.prod(evals)

2.0941156826060654

In [24]:
# LOW RANK
evals, evecs = np.linalg.eigh(A @ A.T)
evals

array([-1.28896079e-16,  1.57519016e-16,  3.24397802e-01,  2.01186940e+00,
        3.20865468e+00])

In [25]:
np.prod(evals)

-4.2518052850505415e-32

In [26]:
# DIAGONALIZATION
A = np.array([[-2, 1], [12, -3]])
evals, evecs = np.linalg.eig(A)

In [27]:
evecs @ np.diag(evals) @ np.linalg.inv(evecs)

array([[-2.,  1.],
       [12., -3.]])

In [28]:
# MATRIX POWERS
A @ A @ A

array([[ -92,   31],
       [ 372, -123]])

In [29]:
evecs @ np.diag(evals**3) @ np.linalg.inv(evecs)

array([[ -92.,   31.],
       [ 372., -123.]])

In [30]:
# SQUARE ROOT OF A MATRIX
X = np.random.randn(3, 3)
A = X.T @ X
evals, evecs = np.linalg.eig(A)

rt = evecs @ np.diag(np.sqrt(evals)) @ np.linalg.inv(evecs)

In [31]:
A

array([[12.48533881, -2.86000831,  1.41941746],
       [-2.86000831,  0.75347724,  0.02507965],
       [ 1.41941746,  0.02507965,  1.97360335]])

In [32]:
# IS A^1/2 A^1/2 = A?
rt @ rt

array([[12.48533881, -2.86000831,  1.41941746],
       [-2.86000831,  0.75347724,  0.02507965],
       [ 1.41941746,  0.02507965,  1.97360335]])

In [33]:
# NEGATIVE ROOT
negrt = evecs @ np.diag(evals**(-0.5)) @ np.linalg.inv(evecs)

In [34]:
# IS A^(-1/2) * A * A^(-1/2) = I?
negrt @ A @ negrt

array([[ 1.00000000e+00, -7.80115397e-16,  1.75742060e-17],
       [-4.07007059e-15,  1.00000000e+00,  9.71490675e-16],
       [ 5.44848885e-16,  8.65828317e-17,  1.00000000e+00]])

In [35]:
# IS A^1/2 * A^(-1/2) = I?
# (A^p)^-1 = (A^-1)^p = A^-p
rt @ negrt

array([[ 1.00000000e+00,  1.60624183e-16,  6.29707866e-17],
       [ 1.03179652e-16,  1.00000000e+00, -7.56856115e-17],
       [-1.02626276e-17,  8.65828317e-17,  1.00000000e+00]])

In [42]:
# Relationship between rank and non-zero eigenvalues
# "Almost" a constant multiple
A = np.random.randn(3, 3)
A[:,2] = 10 * A[:,1] + np.random.randn(3) * 0.000001
A

array([[ 0.26739664, -0.09768673, -0.97686648],
       [-0.68783359, -0.01273299, -0.12732961],
       [ 0.06350043,  0.46523211,  4.65232002]])

In [43]:
evals, evecs = np.linalg.eig(A)
evals

array([-1.80283098e-07,  2.66216758e-01,  4.64076710e+00])

In [ ]:
# Exercise: try some experiments with SVD to show that
# rank = number of non-zero eigenvalues

![](https://deeplearningcourses.com/notebooks_v3_pxl?sc=U79P7NnBNiFd_XtiGVhbMQ&n=Eigenvalues)