In [ ]:
import numpy as np

## Checking the rank of a matrix

In [ ]:
# Simple example
A = np.array([[1, 2], [1, 1]])
np.linalg.matrix_rank(A)

2

In [ ]:
# What if one row/col is *almost* a constant multiple of another?
A = np.array([[1, 1.0000001], [1, 1]])
np.linalg.matrix_rank(A)

2

In [ ]:
# we can find the rank by looking at how many non-zero values are in S
A = np.array([[1, 2], [1, 1]])
U, S, VT = np.linalg.svd(A)
S

array([2.61803399, 0.38196601])

In [ ]:
A = np.array([[1, 2], [2, 4]])
U, S, VT = np.linalg.svd(A)
S

array([5.00000000e+00, 1.98602732e-16])

## Matrix Decompositions

In [ ]:
L = np.array([[1, 0], [2, 1]])
A = L @ L.T
A

array([[1, 2],
       [2, 5]])

In [ ]:
# Exercise on your own: Check that A is PD

In [ ]:
np.linalg.cholesky(A)

array([[1., 0.],
       [2., 1.]])

In [ ]:
import scipy
A = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])
P, L, U = scipy.linalg.lu(A) # A = P @ L @ U

In [ ]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [ ]:
L

array([[1. , 0. , 0. ],
       [0.2, 1. , 0. ],
       [0.6, 0.5, 1. ]])

In [ ]:
U

array([[5. , 6. , 7. ],
       [0. , 0.8, 1.6],
       [0. , 0. , 0. ]])

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
P, L, U = scipy.linalg.lu(A)

In [ ]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [ ]:
L

array([[1. , 0. ],
       [0.2, 1. ],
       [0.6, 0.5]])

In [ ]:
U

array([[5. , 6. ],
       [0. , 0.8]])

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
Q, R = np.linalg.qr(A)

In [ ]:
Q

array([[-0.16903085,  0.89708523],
       [-0.50709255,  0.27602622],
       [-0.84515425, -0.34503278]])

In [ ]:
R

array([[-5.91607978, -7.43735744],
       [ 0.        ,  0.82807867]])

In [ ]:
Q @ Q.T

array([[ 0.83333333,  0.33333333, -0.16666667],
       [ 0.33333333,  0.33333333,  0.33333333],
       [-0.16666667,  0.33333333,  0.83333333]])

In [ ]:
Q.T @ Q

array([[1.00000000e+00, 6.18439648e-17],
       [6.18439648e-17, 1.00000000e+00]])

## Frobenius Norm and Trace

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
np.linalg.norm(A)

9.539392014169456

In [ ]:
np.sqrt(np.trace(A @ A.T))

9.539392014169456

In [ ]:
np.sqrt(np.trace(A.T @ A))

9.539392014169456

## Investigating SVD

In [ ]:
# Let's find the best rank 1 approximation
A = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9]])
U, S, VT = np.linalg.svd(A)

In [ ]:
U

array([[-0.18923073, -0.81497959,  0.37684105, -0.39748059],
       [-0.36846753, -0.40525508, -0.2061902 ,  0.81085486],
       [-0.54770432,  0.00446943, -0.71814276, -0.42926795],
       [-0.72694112,  0.41419393,  0.54749191,  0.01589368]])

In [ ]:
S

array([1.91491774e+01, 1.14411715e+00, 1.08189867e-15])

In [ ]:
VT

array([[-0.47635167, -0.57203953, -0.66772738],
       [ 0.77873129,  0.07812881, -0.62247367],
       [-0.40824829,  0.81649658, -0.40824829]])

In [ ]:
U @ U.T

array([[ 1.00000000e+00, -1.49623437e-16,  9.19305943e-17,
         2.76029300e-16],
       [-1.49623437e-16,  1.00000000e+00,  2.76362030e-17,
         1.54733747e-16],
       [ 9.19305943e-17,  2.76362030e-17,  1.00000000e+00,
        -3.56629509e-17],
       [ 2.76029300e-16,  1.54733747e-16, -3.56629509e-17,
         1.00000000e+00]])

In [ ]:
z = U @ U.T
I = np.eye(len(z))
np.allclose(z, I)

True

In [ ]:
z = VT @ VT.T
I = np.eye(len(z))
np.allclose(z, I)

True

In [ ]:
np.linalg.matrix_rank(A.T @ A)

2

In [ ]:
np.linalg.matrix_rank(A @ A.T)

2

In [ ]:
np.linalg.matrix_rank(A)

2

Another way to express SVD:

$$ USV^T = \sum_{i=1}^n \sigma_i u_i v_i^T $$

In [ ]:
# rank 1 approximation
Ahat1 = S[0] * np.outer(U[:,0], VT[0,:])
Ahat1

array([[1.72611407, 2.07284981, 2.41958555],
       [3.36106599, 4.03622515, 4.7113843 ],
       [4.99601792, 5.99960048, 7.00318305],
       [6.63096985, 7.96297582, 9.2949818 ]])

In [ ]:
# rank 2 approximation
Ahat2 = S[0] * np.outer(U[:,0], VT[0,:]) + S[1] * np.outer(U[:,1], VT[1,:])
Ahat2

array([[1., 2., 3.],
       [3., 4., 5.],
       [5., 6., 7.],
       [7., 8., 9.]])

In [ ]:
# what's left?
S[2] * np.outer(U[:,2], VT[2,:])

array([[-1.66444394e-16,  3.32888787e-16, -1.66444394e-16],
       [ 9.10707641e-17, -1.82141528e-16,  9.10707641e-17],
       [ 3.17191652e-16, -6.34383305e-16,  3.17191652e-16],
       [-2.41818023e-16,  4.83636046e-16, -2.41818023e-16]])

In [ ]:
# Exercise: confirm the rank 1 approximation we calculated is the
# best rank 1 approximation

![](https://deeplearningcourses.com/notebooks_v3_pxl?sc=U79P7NnBNiFd_XtiGVhbMQ&n=Matrix+Rank)